name: Tests
on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: '3.12'
      - name: Install requirements
        run: pip install -r dev-requirements.txt
      - name: Check coding standards
        run: flake8 .

  test:
    needs: lint
    strategy:
      matrix:
        include:
          - ckan-version: "2.10"
            solr-image: "ckan/ckan-solr:2.10"
            harvest-ref: "v1.5.6"
            scheming-ref: "release-3.0.0"
          - ckan-version: "2.11"
            solr-image: "ckan/ckan-solr:2.11-solr9"
            harvest-ref: "v1.6.2"
            scheming-ref: "release-3.1.0"
      fail-fast: false

    name: CKAN ${{ matrix.ckan-version }}
    runs-on: ubuntu-latest
    container:
      image: ckan/ckan-dev:${{ matrix.ckan-version }}
      options: --user root
    services:
      solr:
        image: ${{ matrix.solr-image }}
      postgres:
        image: ckan/ckan-postgres-dev:${{ matrix.ckan-version }}
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
      redis:
        image: redis:3
    env:
      CKAN_SQLALCHEMY_URL: postgresql://ckan_default:pass@postgres/ckan_test
      CKAN_DATASTORE_WRITE_URL: postgresql://datastore_write:pass@postgres/datastore_test
      CKAN_DATASTORE_READ_URL: postgresql://datastore_read:pass@postgres/datastore_test
      CKAN_SOLR_URL: http://solr:8983/solr/ckan
      CKAN_REDIS_URL: redis://redis:6379/1

    steps:
    - uses: actions/checkout@v6

    - name: Install requirements
      run: |
        pip install --upgrade pip
        # scheming
        pip install -e "git+https://github.com/ckan/ckanext-scheming.git@${{ matrix.scheming-ref }}#egg=ckanext-scheming"
        pip install -r "https://raw.githubusercontent.com/ckan/ckanext-scheming/${{ matrix.scheming-ref }}/requirements.txt"
        # harvest
        pip install -e "git+https://github.com/ckan/ckanext-harvest.git@${{ matrix.harvest-ref }}#egg=ckanext-harvest"
        pip install -r "https://raw.githubusercontent.com/ckan/ckanext-harvest/${{ matrix.harvest-ref }}/requirements.txt"
        # DDI
        pip install -r requirements.txt
        pip install -r dev-requirements.txt
        pip install -e .

    - name: Setup DB
      run: |
        ckan -c test.ini db upgrade

    - name: Run tests
      run: pytest --ckan-ini=test.ini --cov=ckanext.ddi --cov-report xml --disable-warnings ckanext/ddi/tests
